services:
  brain:
    build: .
    container_name: sim_brain
    # This allows the container to talk to your Windows host easily
    ports:
      - "7447:7447" 
    volumes:
      # This maps your Windows folder to the Linux folder
      # Any change you make in Windows instantly appears in Linux
      - .:/app
    # Improve shared memory for Zenoh
    shm_size: '2gb'